.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ARCHWIKI\-RS" "1" "April 2024" ""
.SH "NAME"
\fBarchwiki\-rs\fR \- Read pages from the ArchWiki
.SH "SYNOPSIS"
\fBarchwiki\-rs <COMMAND>\fR
.SH "DESCRIPTION"
.SH "EXAMPLES"
.SH "SUB COMMANDS"
\fBarchwiki\-rs read\-page <PAGE> [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs search <QUERY> [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs list\-pages [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs list\-categories [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs list\-languages [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs sync\-wiki [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs local\-wiki <LOCATION> [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs info [OPTIONS]\|\.\|\.\|\.\fR
.P
\fBarchwiki\-rs completions [OPTIONS]\|\.\|\.\|\.\fR
.SH "AUTHOR"
June L\. Gschwantner lucygschwantner@gmail\.com
