.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ARCHWIKI\-RS\-LOCAL\-WIKI" "1" "April 2024" ""
.SH "NAME"
\fBarchwiki\-rs\-local\-wiki\fR \- Download a copy of the ArchWiki
.SH "SYNOPSIS"
.SH "DESCRIPTION"
.SH "EXAMPLES"
.SH "AUTHOR"
June L\. Gschwantner lucygschwantner@gmail\.com
