.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ARCHWIKI\-RS\-COMPLETIONS" "1" "April 2024" ""
.SH "NAME"
\fBarchwiki\-rs\-completions\fR \- Generate scripts for shell auto\-completion
.SH "SYNOPSIS"
\fBarchwiki\-rs completions <SHELL>\fR
.SH "DESCRIPTION"
Print a shell script that enable tab completion for the specified shell\. Write the output of this command to where auto\-completion scripts are stored for your shell\. For \fBoh\-my\-zsh\fR that would be \fB~/\.oh\-my\-zsh/completions/_archwiki\-rs\fR\.
.SH "EXAMPLES"
\fBarchwiki\-rs completions fish\fR
.IP "" 4
Generate auto\-completion scripts for the fish shell\.
.IP "" 0
.SH "AUTHOR"
June L\. Gschwantner lucygschwantner@gmail\.com
