.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ARCHWIKI_RS\-SEARCH" "1" "April 2024" ""
.SH "NAME"
\fBarchwiki_rs\-search\fR
.P
archwiki\-rs\-search \-\- Search the ArchWiki for pages
.SH "SYNOPSIS"
\fBarchwiki\-rs search <QUERY> [OPTIONS]\|\.\|\.\|\.\fR
.SH "DESCRIPTION"
Search for content on the ArchWiki\. Can either search for page titles that match the \fBquery\fR (default) or search for text content contain in pages that matches the \fBquery\fR string\. Pass the \fB\-t|\-\-text\-search\fR option to enable text search\.
.P
Searches are made directly through the ArchWiki search API which is just a deployment of the MediaWiki search API \fIhttps://www\.mediawiki\.org/wiki/API:Searchttps://www\.mediawiki\.org/wiki/API:Search\fR\. For better and for worse this means the results are the same as directly searching on the ArchWiki\.
.SH "EXAMPLE"
\fBarchwiki\-rs search "Neovim"\fR
.IP "" 4
Search for pages that have a similar name to "Neovim" and output a table containing the names and URLs of any pages found\. By default a maximum of 5 items are returned\. You can override this limit with the \fB\-L|\-\-limit\fR option\.
.IP "" 0
.P
\fBarchwiki\-rs search "/usr/share" \-\-text\-search \-\-snippet\-format markdown \-\-json\fR
.IP "" 4
Search for pages that contain text matchs for the query string "/usr/share" and output a JSON array where each element containings a \fBtitle\fR and a \fBsnippet\fR field\. The \fBsnippet\fR field contains the text that was matched by the query and is formated as \fBmarkdown\fR because of the value of the \fB\-\-snippet\-format\fR option\.
.IP "" 0

