.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ARCHWIKI\-RS\-SYNC\-WIKI" "1" "April 2024" ""
.SH "NAME"
\fBarchwiki\-rs\-sync\-wiki\fR \- Download metadata information about the pages and categories on the ArchWiki
.SH "SYNOPSIS"
.SH "DESCRIPTION"
.SH "EXAMPLE"

